- name: Installing keystone and its prerequisites in CentOS
  yum:
    name:
      - openstack-keystone 
      - httpd 
      - mod_wsgi 
      - openstack-utils
    skip_broken: yes
  when: ansible_distribution == "CentOS"

- name: Install Keystone in Ubuntu
  apt:
    name:
      - keystone
      - apache2
      - php
      - libapache2-mod-php
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Start and enable keystone service for Ubuntu
  service:
    name: keystone
    state: started
    enabled: yes
  when: ansible_distribution == "Ubuntu"
